### ISSUE TITLE
Animation of star on panel buttons

### ISSUE THREAD

**Issue by zdechlak** [freeserf/freeserf#106]
star in the original game - is animated

![star](https://f.cloud.github.com/assets/2237225/690873/d48394e6-db44-11e2-80bb-48b04f05e898.jpg)

**Comment by wdigger** [comment]
Star is animated only in Amiga game, DOS version have no such resources (animation phases) at all.
I think it will possible only when Amiga resources loading will be implemented.

**Comment by wdigger** [comment]
I think it makes no sense to make the behavior dependent on resources. Indication will remain like in DOS game.
