### ISSUE TITLE
Add x2 Zoom to Main Menu

### ISSUE THREAD

**Issue by Richard-L** [freeserf/freeserf#129]
Freeserf is in 100% pixel size at the moment making it very hard to use, especially in window mode which omits the stretching and interpolation taking place in fullscreen mode.

The main menu on startup is borderline usable because it's so small. I suggest doubling its pixel size. Potentially apply smart anti-aliasing filter to zoomed interface.

EDIT: I take it only mods can apply tags? Wanted to add "graphics".

**Comment by alexkazik** [comment]
It would be even better if you could zoom the windows (menu, map) separately from the game world.
Extra bonus: When the map is zoomed show the contents in higher resolution.

**Comment by zdechlak** [comment]
New Windows build ?

2015-07-03 17:25 GMT+02:00 ALeX Kazik <notifications@github.com>:

**Comment by wdigger** [comment]
Realized in PR #188
