### ISSUE TITLE
Limit to number of buildings/flags/.. is too low?

### ISSUE THREAD

**Issue by zdechlak** [freeserf/freeserf#134]
suddenly during the game
I can not build houses

- save: https://docs.google.com/file/d/0B2CGgMeJSKB2TFIyTEktLXF3eGs/edit?usp=sharing

- version freeserf-20130704-0833

limit of buildings?
after burning one
I can build one
but I can not build more than one: P

- video: http://www.youtube.com/watch?v=kvwStjJbFQg&feature=youtu.be

**Comment by genodeftest** [comment]
I'd vote for doubling the number of buildings and thus doubling the number of flags. I haven't run into any other limits so far, I guess they are good.

**Comment by wdigger** [comment]
We have no limitation after refactoring (2^32 in fact :) ).
