### ISSUE TITLE
Farmer spread too much fields

### ISSUE THREAD

**Issue by wdigger** [freeserf/freeserf#153]
It's looks like farmer sow to already sown places. And in any case it's much more then in original game.

**Comment by jonls** [comment]
Was this fixed already? I've been trying to reproduce this issue but I can't see any difference between the behavior of the farmer in the original game and Freeserf. The size of the areas that are sown are exactly the same and I haven't observed any cases where the farmer sows in existing fields.

**Comment by wdigger** [comment]
It's strange, but no more field spam. Fixed indirectly.
