### ISSUE TITLE
Too many building materials requested / sent

### ISSUE THREAD

**Issue by Wolfe-Lyon** [freeserf/freeserf#192]
- Compiling with g++ on xubuntu.

After compiling, I start a new game, construct the castle, then order a lumberjack hut nearby. Upon connecting the lumberjack hut site to the castle via a road, a seemingly unlimited number of planks are removed from the castle and delivered to the construction site, even though the construction should only require two planks.

I have used git bisect to identify the first commit in which this issue occurs for me:
e3021e03bfecb58cbeea72e00e3fade5f642da12 is the first bad commit

**Comment by Wolfe-Lyon** [comment]
By printing out the values of variables **stock[0].requested** ("requested"), **stock[0].available** ("available") and **stock[0].maximum** ("maximum") in the function **building_t::update_unfinished**, I've spotted the following:

- As soon as the construction site is connected to the castle via a road:
   - requested = 0
   - available = 0
   - maximum = 2

- Immediately after first plank delivered to site:
   - requested = -1
   - available = 1
   - maximum = 2

- Immediately after builder picks up plank and begins using it:
   - requested = -1
   - available = 0
   - maximum = 1

- Immediately after second plank delivered to site:
   - requested = -2
   - available = 1
   - maximum = 1

It seems that the requested property is being decremented, but is never initially set (to 2 in the case of a lumberjack hut) so becomes negative. This results in the check total_planks < maximum always being true, and thus more planks being requested / delivered.

The same issue affects delivery of stone to building sites that require it.

Also, upon further testing, after construction of an outpost, a steady stream of knights leave the castle, walk up to the door of the outpost and then turn around and return to the castle. I assume this is a related issue where the number of requested knights becomes progressively more negative.

This issue is likely to affect pretty much everything that can uses the requested property.

**Comment by wdigger** [comment]
I can't reproduce this bug. Please, insert logging for all places when requested is decreased and try to find a reason.

**Comment by Wolfe-Lyon** [comment]
I've inserted logging statements at each location in building.cc where requested is decremented. The log output indicates that requested is being decremented in the function **building_t::requested_resource_delivered**. Unfortunately my knowledge of C and C++ is limited so I cannot provide a fix, however the issue appears to be that the requested variable is not being initialised to 2, thus it starts off as zero and gets progressively lower:

[building] requested_resource_delivered, stock[i].requested decremented to '-1'...
[building] requested_resource_delivered, stock[i].requested decremented to '-2'...
[building] requested_resource_delivered, stock[i].requested decremented to '-3'...
[building] requested_resource_delivered, stock[i].requested decremented to '-4'...
[building] requested_resource_delivered, stock[i].requested decremented to '-5'...
[building] requested_resource_delivered, stock[i].requested decremented to '-6'...

As you are not able to reproduce this, it could be a platform-specific issue. That seems likely given that this is a pretty serious issue that has not been spotted before.

**Comment by Wolfe-Lyon** [comment]
The bug goes away when I run configure with --enable-debug. In this case, I get lots of messages about "comparison between signed and unsigned integer expressions". It looks like my compiler and/or its (default) configuration could be to blame.
