### ISSUE TITLE
No rule to make target 'src/mission.c', needed by 'src/mission.o'.

### ISSUE THREAD

**Issue by genodeftest** [freeserf/freeserf#206]
When trying to compile freeserf from master, it fails:

```
$ LC_ALL=C make
FREESERF_VERSION = 
VCS_VERSION = v0.1.1-238-g70b98c1
Updating version file.
make  all-am
make[1]: Entering directory '/home/username/src/freeserf'
  CXX      src/freeserf.o
  CXX      src/data.o
make[1]: *** No rule to make target 'src/mission.c', needed by 'src/mission.o'.  Stop.
make[1]: Leaving directory '/home/username/src/freeserf'
Makefile:370: recipe for target 'all' failed
make: *** [all] Error 2

```

I've done `git clean -d` already.

**Comment by wdigger** [comment]
Do you really have a clean version? It seems you don't remove old generated makefile before update.

**Comment by genodeftest** [comment]
`git status` just shows one completely unrelated text file.
Other than this single file, I'm at freeserf/master, commit 70b98c1411e62f44512c5fb4addc8827024abc59

**Comment by genodeftest** [comment]
Ok, sorry, the issue is somewhere on my side. On a clean `git clone`, `./bootstrap`, `./configure`, `make` it works fine. I'll have to remove the files ignored by .gitignore too.

`$ git clean -d -X -i` did the job.
