### ISSUE TITLE
Game randomness

### ISSUE THREAD

**Issue by jonls** [freeserf/freeserf#218]
I was trying to do some refactoring of the random number generators in `map_t` and `game_t` and I realized that the `random_int()` method on `game_t` uses the state in `init_map_rnd` (https://github.com/freeserf/freeserf/blob/master/src/game.cc#L2268). However, `game_t` also has another random state called `rnd` but this does not seem to be used anymore. Also, `init_map_rnd` does not seem to be saved in the save game file but `rnd` _is_ saved even though it is not used. I think `random_int` should either be changed to use `rnd` or instead `init_map_rnd` should be saved in the save game.

Does this sound right? @wdigger

**Comment by wdigger** [comment]
I think strict sequence of randomness has meaning only when map generating. When map is generated we may use C++ random or realise static random_state_t::random().

**Comment by jonls** [comment]
I disagree. I think there are some important advantages to having the randomness state explicitly part of the game state. For networking, having the randomness state means that a client can simulate the game updates independently of the server instead of constantly having to synchronize the state. Only the randomness state has to be synchronized at the beginning of the game. Having the game progress based on the random state also means that it is easy to save a replay of a game just by storing the initial random state and the sequence of actions that the players are taking in the game.

I'm almost certain that the random state used to be saved correctly in the save game. Do you know if `random_int()` was changed from using `rnd` to `init_map_rnd`?

**Comment by jonls** [comment]
`random_int()` was reverted to using `rnd` in #225
