### ISSUE TITLE
Build error: run configure - syntax error near unexpected token `-std=c++11

### ISSUE THREAD

**Issue by ds2k5** [freeserf/freeserf#312]
Hi, 
how to fix this Problem ?

$ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for SDL2... yes
checking for SDL2_mixer... no
checking for libxmp... no
checking whether to enable assertions... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking byteswap.h usability... yes
checking byteswap.h presence... yes
checking for byteswap.h... yes
checking endian.h usability... yes
checking endian.h presence... yes
checking for endian.h... yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking sys/endian.h usability... no
checking sys/endian.h presence... no
checking for sys/endian.h... no
./configure: line 4223: syntax error near unexpected token `-std=c++11,'
./configure: line 4223: `AX_CHECK_COMPILE_FLAG(-std=c++11, CXXFLAGS="$CXXFLAGS -std=c++11")'

gcc (GCC) 6.3.1 20170109
g++ (GCC) 6.3.1 20170109
automake (GNU automake) 1.15

glibc 2.24-2

Using: Manjaro Linux

Thanks

**Comment by ds2k5** [comment]
opend the file: configure an removed the line:

AX_CHECK_COMPILE_FLAG(-std=c++11, CXXFLAGS="$CXXFLAGS -std=c++11")

then the configure script runs without error, but ... make have now errors

when i download via git clone insted of download the zip
then it worked fine without the Line:

AX_CHECK_COMPILE_FLAG(-std=c++11, CXXFLAGS="$CXXFLAGS -std=c++11")

in configure file

and make runs fine without error

**Comment by wdigger** [comment]
Pls check then "autoconf-archive" package is installed.
