### ISSUE TITLE
Colors of flags

### ISSUE THREAD

**Issue by zdechlak** [freeserf/freeserf#320]
The newest freeserf has:

- color errors players
- many problems related to this
- graphical glyphs / Amiga / DOS

![image](https://cloud.githubusercontent.com/assets/2237225/24654469/02a40130-193a-11e7-9217-baa514a41e7e.png)

**Comment by wdigger** [comment]
1. Some Amiga resources unpacking wrong way. I have no idea how to fix this for now.
2. Please, clarify problems with player colours, how to reproduce?
3. What's wrong with DOS glyphs?

**Comment by zdechlak** [comment]
1. DOS /  Player 1-4 has the same flag color
2.  Sometimes the flag is black

![image](https://cloud.githubusercontent.com/assets/2237225/24763643/3fe9bb02-1af2-11e7-9dd7-fc72973543d5.png)

**Comment by zdechlak** [comment]
in the amiga files this same problem

![image](https://cloud.githubusercontent.com/assets/2237225/24764403/8821974e-1af4-11e7-8ffb-bd60d09e77b4.png)

i can bulid more than 4 castles 
The colors of the flags are repeated or black

**Comment by zdechlak** [comment]
contant me please b.godzinski@gmail.com

**Comment by wdigger** [comment]
New issue #321 created for problem with players

**Comment by zdechlak** [comment]
Problem flag / number of players < is in custom game

![image](https://cloud.githubusercontent.com/assets/2237225/25063043/b5e4c1e2-21d9-11e7-985a-c7ae4b49afc1.png)

In mission games the colors of the flag are all ok

![image](https://cloud.githubusercontent.com/assets/2237225/25063064/213eaf84-21da-11e7-9256-e61189596ead.png)
