### ISSUE TITLE
Understanding legacy settlers save game format - how main castle knights are stored

### ISSUE THREAD

**Issue by ryan-de-boer** [freeserf/freeserf#376]
I was trying to understand the file format from settlers. In particular I wanted to know where the number of knights are in the main building (for each rank). I found where the resources are and how they are stored but I wanted to know where the knights were too. Since freeserf appears to support save games from the original settlers (legacy) from reading the source code, you may already know how the number of knights are stored?

UPDATE:
- The resources are just counters in the save game, but I was thinking maybe main castle knights aren't just a counter, but maybe entire settler (serf) objects are created and saved and their count is just summed and displayed in game. So maybe you'd need to add extra serf objects to create a valid save with more knights (this would explain why the file size grows when new knights are created in the main castle). This makes it a more complex problem to solve than the resources.
- Since I got freeserf 0.1.1 loading a legacy settlers save game the source might help me understand the legacy file format better. Any tips on how the knights in the main castle are stored in the legacy save game format would be useful though.

**Comment by wdigger** [comment]
Any presented in building (military) knights it's a chain of serfs (linked list). Serf presented as structure in memory. Castle knights are promoted time-by-time, thats why thay are real objects but not an only number in counter.

**Comment by ryan-de-boer** [comment]
Answer verified my suspicions. 
I'll close this for now. 
Assuming the save game issue is fixed and the latest build supports the legacy save format, then the code should be good enough to document the file format.
