### ISSUE TITLE
Can't run freeserf.exe built from 0.1.1 source on windows with cygwin

### ISSUE THREAD

**Issue by ryan-de-boer** [freeserf/freeserf#377]
After compiling 0.1.1 freeserf.exe using cygwin it has this error when I run it:
[sdl-video] Unable to initialize SDL: No available video device.
Any idea how to fix it?

long version:
I unpacked the 0.1.1 source, installed cycwin 64 with these:
autoconf2.5
automake
libsdl1.2-dev 
gcc-g++
make
libSDL_mixer-devel
libSDL_mixer1.2_0

./bootstrap
./configure

modified the Makefile to skip generating VCS_VERSION_FILE
manually created the version file version_vcs.h:
`
#ifndef VERSION_VCS_H
#define VERSION_VCS_H

#define VERSION_VCS "1"

#endif /* VERSION_VCS_H */
`

make

freeserf.exe is compiled successfully

Put all the cygwin dll dependencies in the freeserf.exe folder

I get this when I run it:
[sdl-video] Unable to initialize SDL: No available video device.

I've tried setting up env vars:
$DISPLAY=:0
$SDL_VIDEODRIVER=directx
But they don't have any effect.

**Comment by wdigger** [comment]
I think thats no chance to fix old release. Try to build and use new one.

**Comment by ryan-de-boer** [comment]
I chose to build that version because it had working save and load functionality which I wanted. The released 0.1.1 binary works fine (has no video device errors) so it must be possible to compile it correctly. The released binary does not require cygwin dlls so it must have been built with something else. 
I had a look at the HEAD and the build mechanism has changed so I guess I can try and build it instead. I really want working save/load functionality.

**Comment by ryan-de-boer** [comment]
I'll close this for now. Focus should be on fixing the save game functionality in the current release.
Assuming the save game issue is fixed then I wont need to build the old one.
