### ISSUE TITLE
blurred graphics

### ISSUE THREAD

**Issue by zdechlak** [freeserf/freeserf#381]
![image](https://user-images.githubusercontent.com/2237225/34989337-735630dc-fac2-11e7-97a1-becefe6db06d.png)

Is it possible to obtain graphics as in the Serflings project?

**Comment by wdigger** [comment]
@zdechlak please, try this. Reopen issue if any problems.
I have no windows with such big resolution, but I may work with mac retina.

**Comment by igroglaz** [comment]
I have this issue too. I zoom in (as I like original 640 x 480) and game become blurred. When I play DOSBox version with original resolution - all sharp
