### ISSUE TITLE
Zooming is unsupported on keyboard layouts where the [ ] marks are on a modifier button.

### ISSUE THREAD

**Issue by GraionDilach** [freeserf/freeserf#388]
On the Hungarian keyboard layout - https://en.wikipedia.org/wiki/QWERTZ#Hungary - I was unable to zoom in or out - AltGr-F toggles fullscreen and AltGr-G enables some sort of a debug view.  Switching to the English layout changed the functions of the Hungarian ő and ú buttons to be able to do such as intended.

Used the Windows x86 build of master along with `spau.pa` at the time of posting. (Presumably commit 88f109c)

**Comment by GraionDilach** [comment]
I'd like to also stress though that this project literally made my day. Settlers 1 is my favourite from the series and I am amazed by what this project achieved already.

**Comment by GraionDilach** [comment]
Seems to be related to/duplicate of #148.

**Comment by jonls** [comment]
Thanks for reporting. Yes, this seems to be a duplicate of #148 so let's continue with that issue.
