### ISSUE TITLE
menu ordering issue for garrison min/max

### ISSUE THREAD

**Issue by tlongstretch** [freeserf/freeserf#407]
in menu for knight garrison levels min/max (based on distance from enemy) the values are backwards from DOS game, max is normally on top and min on bottom

**Comment by tlongstretch** [comment]
This is still an issue in the master branch.  I realize it is very minor.

**Comment by wdigger** [comment]
Please, provide a screenshot, I don't understand which concrete place you mean.

**Comment by tlongstretch** [comment]
![freeserf_garrison_size](https://user-images.githubusercontent.com/45954803/51127060-9cb2d180-17f2-11e9-855b-5bbc7bf9e13e.PNG)
![dos_serf_city_garrison_size](https://user-images.githubusercontent.com/45954803/51127072-a2a8b280-17f2-11e9-9643-1163a2e4a58a.PNG)
