### ISSUE TITLE
knight rank

### ISSUE THREAD

**Issue by tlongstretch** [freeserf/freeserf#408]

**Comment by tlongstretch** [comment]
this and all other Dec18 2018 issue reports from git clone of release-0.2 x86-compiled with MS VS 2017 on win7 using spae.pa, sdl2.0.9, sdl-mixer2.0.4

**Comment by wdigger** [comment]
Thank you very much for participating!
If this is not too difficult, please try to reproduce these problems on the release-0.3 branch.
It seems to me that some have already been fixed.
Maybe I will fix the rest and make the new release.

**Comment by tlongstretch** [comment]
Will do.  I just figured out how to get the master branch to compile.   I
wasn't aware of the release-0.3 branch until you mentioned it.  I am
starting a new game now with the master branch, I will close out any issues
I created that are already fixed

**Comment by tlongstretch** [comment]
I see the correct knight rankings in master branch.  Closing this.
