### ISSUE TITLE
Question about opponents, AI, network play

### ISSUE THREAD

**Issue by tlongstretch** [freeserf/freeserf#421]
I can't find a good forum for general discussion so I will post here.  

I notice in the freeserf code there is detailed code for knight combat.  However, with no AI opponents and no hot-seat 2 player (which I've never seen even in the original Settlers 1 game) nor network play, how is this code being executed and tested?  Are you manually crafting levels with opposing players using an editor?  Or importing savegames containing AI opponents from the original game?  I tried doing this and got an error when trying to load a savegame from DOS Serf City.

Does any code exist for AI or network play at this time?  Even preliminary?  

At this point the game appears to work very well for a solo player, but there are no opponents to play against.

**Comment by wdigger** [comment]
And, please, file an issue for crash on original saved game loading. Attach save file if it possible.

**Comment by tlongstretch** [comment]
Thanks for explanation.  I am going to look into the savegame issue more

**Comment by tlongstretch** [comment]
I just discovered that you can switch players!  I did not know this was possible (using "j" key).   You should mention this in the main README.

**Comment by tlongstretch** [comment]
I have begun writing a rudimentary AI.  I will post details on the wiki
