### ISSUE TITLE
Game crashes on startup when using Amiga files

### ISSUE THREAD

**Issue by Vershner** [freeserf/freeserf#454]
Just download the current compiled Windows x64 build and it works with the PC spae.pa, but if I try the Amiga files it crashes with a white screen on startup. It does manage to load the cursor but nothing more. 
I tested files from two different sources, firstly taken from my actual Amiga, then from an ADF on the internet. Is there something I need to do to tell the game to use the Amiga files? 

"freeserf -h"  as suggested in the readme does nothing.

**Comment by Vershner** [comment]
Further testing with x86 version shows the same behaviour. 
I found that freeserf.exe doesn't seem to be outputting to the console, so "freeserf -h" produces nothing, but "freeserf -h >help.txt" does output the help. 
So, with "FreeSerf.exe -g amiga -d 1 >log.txt" I was able to get the following log: 

Info: [main] freeserf 0.3.bc5e2d2
Info: [data] Looking for game data in 'amiga/SPAE.PA'...
Info: [data] Looking for game data in 'amiga/SPAF.PA'...
Info: [data] Looking for game data in 'amiga/SPAD.PA'...
Info: [data] Looking for game data in 'amiga/SPAU.PA'...
Info: [data] Looking for game data in 'amiga/gfxheader'...
Info: [data] Looking for game data in 'amiga/gfxfast'...
Info: [data] Looking for game data in 'amiga/gfxchip'...
Info: [data] Game data found in 'amiga'...
Debug: [data] Data file 'gfxfast' loaded (size = 192196)
Debug: [data] Data file 'gfxchip' loaded (size = 233366)
Debug: [data] Data file 'gfxpics' loaded (size = 114256)
Info: [main] Initialize graphics...
Info: [video] Initializing "sdl".
Info: [video] Available drivers:
Info: [video] 	windows
Info: [video] 	dummy
Info: [video] Initialized with SDL 2.0.8 (driver: windows)
Info: [audio] Initializing "sdlmixer".
Info: [audio] Available drivers:
Info: [audio] 	wasapi
Info: [audio] 	directsound
Info: [audio] 	winmm
Info: [audio] 	disk
Info: [audio] 	dummy
Info: [audio] Initialized with SDL 2.0.8 (driver: wasapi)
Info: [audio:SDL_mixer] Initializing SDL_mixer 2.0.2
Info: [audio:SDL_mixer] Initialized
Info: [audio:SDL_mixer] Playing MIDI track: 0
Info: [audio:SDL_mixer] Playing MIDI track: 1
Info: [audio:SDL_mixer] Playing MIDI track: 2
Info: [audio:SDL_mixer] Playing MIDI track: 3
Info: [audio:SDL_mixer] Playing MIDI track: 4
Info: [audio:SDL_mixer] Playing MIDI track: 0
Info: [audio:SDL_mixer] Playing MIDI track: 1
Info: [audio:SDL_mixer] Playing MIDI track: 2
Info: [audio:SDL_mixer] Playing MIDI track: 3
Info: [audio:SDL_mixer] Playing MIDI track: 4

... these last 5 lines then repeat infinitely.

**Comment by wdigger** [comment]
Please, send your data files to wicked_digger@mail.ru, I try to resolve this.
It seems you have other data than mine, may be other language.
Thank you for participate!

**Comment by Vershner** [comment]
Files sent.
