### ISSUE TITLE
x64 download error

### ISSUE THREAD

**Issue by paulikappi** [freeserf/freeserf#464]
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:7c3eb7b0-d01e-0049-3569-0aa66d000000 Time:2020-04-04T10:12:05.7231221Z
</Message>
</Error>

**Comment by tlongstretch** [comment]
Works for me, just tried Debug and Release.  Maybe transient problem with github?

**Comment by wdigger** [comment]
Works fine for last release artefacts.
