### ISSUE TITLE
iterator invalidation when calling update_building on burning building?

### ISSUE THREAD

**Issue by tlongstretch** [freeserf/freeserf#466]
While testing my AI I kept getting incompatible vector iterator errors, which is usually indication that something non-thread safe invalidated a foreach loop in progress.  In this case though it looks like it is the Freeserf code itself.  I might be mistake here, but the issue I see is that Game::update_buildings ends up calling delete_building on burning buildings while iterating over all buildings, invalidating the iterator.   I added a work-around, marking buildings due to be deleted in a new vector and doing those after the rest of the buildings are updated.

original code:
```
  Buildings::Iterator i = buildings.begin();
  while (i != buildings.end()) {
	  Building *building = *i;
	  ++i;
	  building->update(tick);
  }
```

my code w/ work-around:
  ```
  Buildings::Iterator i = buildings.begin();
  std::vector<Building*> buildings_to_delete;
  while (i != buildings.end()) {
	  Building *building = *i;
	  ++i;
	  if (building->is_burning()) {
		  uint16_t delta = tick - building->get_tick();
		  int burning_counter = building->get_burning_counter();
		  if (burning_counter < delta) {
			  Log::Verbose["game"] << " inside Game::update_buildings, marking burning building for deletion, skipping it now";
			  buildings_to_delete.push_back(building);
			  continue;
		  }
	  }
	  building->update(tick);
  }
  for (Building *building : buildings_to_delete) {
	  building->update(tick);
  }
```

**Comment by wdigger** [comment]
It's the same as #457.

**Comment by wdigger** [comment]
Duplicate #457
