### ISSUE TITLE
dead knight animation missing

### ISSUE THREAD

**Issue by tlongstretch** [freeserf/freeserf#467]
When a knight loses a battle there should be an animation where they become an angel and fly away.  This seems to be missing, when a battle is lost the loser simply disappears.

**Comment by tlongstretch** [comment]
I see this only when the a knight defending a building dies.   In other scenarios the animation plays normally

**Comment by tlongstretch** [comment]
I found the cause and fixed in my fork.  The viewport.cc draw_active_serf  section "Draw additional serf" was missing a valid state Serf::StateAttackingVictory.  Adding it fixes the missing animation when an attacker is victorious at an enemy building and the enemy dies.  The free-fight animations already worked fine.

  /* Draw additional serf */
  if (serf->get_state() == Serf::StateKnightEngagingBuilding ||
      serf->get_state() == Serf::StateKnightPrepareAttacking ||
      serf->get_state() == Serf::StateKnightAttacking ||
      serf->get_state() == Serf::StateKnightPrepareAttackingFree ||
      serf->get_state() == Serf::StateKnightAttackingFree ||
      serf->get_state() == Serf::StateKnightAttackingVictoryFree ||
      serf->get_state() == Serf::StateKnightAttackingDefeatFree ||
      _serf->get_state() == Serf::StateKnightAttackingVictory) {_

**Comment by wdigger** [comment]
@tlongstretch is this fix right?

**Comment by tlongstretch** [comment]
Yes, I've never had to revisit it and dead knights have been working for me since 2021!
