### ISSUE TITLE
inactive transporter causes economy to halt

### ISSUE THREAD

**Issue by tlongstretch** [freeserf/freeserf#479]
I see this pretty often and it tends to be game-breaking.  A road appears to have a transporter servicing it but the transporter never does any work and materials pile up.  I have code that detects when a road is missing a transporter, but I am not yet sure how to detect this condition.  I have a savegame showing the condition.  If I load the game this serf is still not transporting.

![stuck serf](https://user-images.githubusercontent.com/45954803/96817015-6d2ff080-13ec-11eb-9a41-55022d4309e0.png)
)
[stucktransp.zip](https://github.com/freeserf/freeserf/files/5419637/stucktransp.zip)

**Comment by p1plp1** [comment]
yes, confirmed, another bug, quick fix is destroy road and make new one, some serf goes there and starts transporting ... sometimes is serf just missing on that not transporting road and never arrive there until u destroy it and create new one on same place ... i think it is caused by inproper serf delete handling...

**Comment by tlongstretch** [comment]
Yes, rebuilding the rode always fixes it, but I am working on AI so I need to detect it with code to work around it.   If cannot figure out what the cause is I will see if I can detect it and trigger whatever resets are done on the road's flags when a road is recreated

**Comment by p1plp1** [comment]
ok,ill try to fix it in next build ill do check paths and test if there is atleast 1 serf assigned or on the road - else ill triger to assign new one ... thats idea ...

**Comment by tlongstretch** [comment]
there is definitely  a serf assigned to the road because you can see a transporter on the road.  However, they aren't doing any work.  I expect this is because the transport arrays are getting messed up.  I don't understand these because they use a lot of bit math.  I am thinking that I can better understand them by looking at the savegame files, though, as they translate a lot of the binary logic into text.

**Comment by sternenzaehler** [comment]
> 
> 
> I see this pretty often and it tends to be game-breaking. A road appears to have a transporter servicing it but the transporter never does any work and materials pile up. I have code that detects when a road is missing a transporter, but I am not yet sure how to detect this condition. I have a savegame showing the condition. If I load the game this serf is still not transporting.
> 
> ![stuck serf](https://user-images.githubusercontent.com/45954803/96817015-6d2ff080-13ec-11eb-9a41-55022d4309e0.png)
> )
> [stucktransp.zip](https://github.com/freeserf/freeserf/files/5419637/stucktransp.zip)

its hard to see from the picture - is this serf "doing nothing" or is he waiting to go the castle flag (both pics look almost the same and hard to tell which one) ?

**Comment by tlongstretch** [comment]
I think this particular issue might be related to a bug in my AI.   I don't tihnk I've seen it in a while since I revamped a bunch of pathfinding logic.  Closing for now
