### ISSUE TITLE
mousewheel zoom is backwards

### ISSUE THREAD

**Issue by tlongstretch** [freeserf/freeserf#486]
Wheel up should zoom in, and wheel down should zoom out.  

I have fixed this in my AI-enabled with this change:
      case SDL_MOUSEWHEEL: {
        SDL_Keymod mod = SDL_GetModState();
        if ((mod & KMOD_CTRL) != 0) {
          // the wheel zoom is backwards unless reversed
          zoom(0.2f * static_cast<float>((event.wheel.y * -1)));
        }
        break;
      }

**Comment by wdigger** [comment]
I'm using Mac and have another vision, for example ;)

**Comment by tlongstretch** [comment]
Fair enough :)

**Comment by tlongstretch** [comment]
I am closing this.  I had set it to opposite in my fork but I may just make it a checkbox option.  Should also do inverted scrolling as some people prefer that
