### ISSUE TITLE
window resize issue when zoomed

### ISSUE THREAD

**Issue by tlongstretch** [freeserf/freeserf#491]
If you resize the game window while zoomed, the game reverts to the original unzoomed resolution.  If you then zoom again, the zoom level is based on the previous zoom level before it was reset, which is unexpected.

But much worse, it seems the mouse cursor effectively breaks when this happens, because the in-game cursor is based on the zoom level while the actual mouse cursor is based on the no-zoom resolution, causing a huge offset between the real mouse cursor and the game cursor.

I see this in linux, I think it is true in windows also but haven't checked.

**Comment by p1plp1** [comment]
yes same problem, maybe more problems under windows :D bad window size handling, another bug
 mouse shoud be recalibrated, when zoom is active, this problem is allready known for me

**Comment by tlongstretch** [comment]
I'll fix it in my fork at some point

**Comment by tlongstretch** [comment]
case SDL_WINDOWEVENT:
        if (SDL_WINDOWEVENT_SIZE_CHANGED == event.window.event) {
          unsigned int width = event.window.data1;
          unsigned int height = event.window.data2;
          gfx.set_resolution(width, height, gfx.is_fullscreen());
          gfx.get_screen_factor(&screen_factor_x, &screen_factor_y);
          // there seems to be a bug where after resize any increased zoom level is not shown
          //  though it is remembered in terms of the relative zoom, so changing zoom adjusts
          //  to the expected new level as if the bug was not there
          // FIXED by below zoom(0); call
          **zoom(0); // this calls zoom but does not adjust**
          notify_resize(width, height);
        }


fixed in Forkserf

**Comment by tlongstretch** [comment]
oops not closed here

**Comment by p1plp1** [comment]
there is defined zoom (float delta) so that shoud be called with float constant: zoom(0.0); i have also problem to compile it with **zoom(0.0); call

**Comment by tlongstretch** [comment]
ah good catch, It compiles fine for me but I agree 0.0 is more correct, updated my code with it
