### ISSUE TITLE
The 'F' key doesn't work in savegame names

### ISSUE THREAD

**Issue by tlongstretch** [freeserf/freeserf#495]

**Comment by tlongstretch** [comment]
this is likely because of 

        // Video
          case SDLK_f:
            if (event.key.keysym.mod & KMOD_CTRL) {
              gfx.set_fullscreen(!gfx.is_fullscreen());
            }
              break;

**Comment by tlongstretch** [comment]
this fix works

          case SDLK_f:
            if (event.key.keysym.mod & KMOD_CTRL) {
              gfx.set_fullscreen(!gfx.is_fullscreen());
            }else{
              // if this isn't handled the 'f' key doesn't work for savegame names
              notify_key_pressed(event.key.keysym.sym, modifier);
            }
            break;

**Comment by p1plp1** [comment]
confirmed, add to bugfix

**Comment by wdigger** [comment]
Fixed
