### ISSUE TITLE
Computer opponents don't exit their castle

### ISSUE THREAD

**Issue by ws1968** [freeserf/freeserf#498]
I compiled the source on a raspberry pi 400 running Manjaro Linux. Compilation gave no errors and almost everyting works. The only thing is that the AI opponents never leave their castle in campaing mode. If I start a normal game then the castle does not get build.
anybody know if I did somthing wrong or is this funtion not available yet?

**Comment by ws1968** [comment]
I realized this has not been implemented yet

**Comment by tlongstretch** [comment]
I have implemented AI in my fork  at https://github.com/forkserf/forkserf/

I have never tested the campaign missions, but the free play works great
