### ISSUE TITLE
Build problem on macOS

### ISSUE THREAD

**Issue by naymapl** [freeserf/freeserf#504]
Hello. I try to build on arm Apple Silicon. 

```
git clone https://github.com/freeserf/freeserf.git
cd freeserf
mkdir build && cd build
cmake ..
make -j8
```

Have no issues but inside build is no build files `/build/FreeSerf.dmg` ??
![Zrzut ekranu 2022-03-9 o 12 14 22](https://user-images.githubusercontent.com/24625283/157431098-df7c047b-8825-4335-b432-13fc6211a60b.jpg)

**Comment by richthedev** [comment]
Look inside the `src` folder, you should see a `FreeSerf.app` file.

**Comment by wdigger** [comment]
Please, use `make package`.
Traditionally `make` default target is building, if you want to do more - use additional targets (install, clean and etc).
