### ISSUE TITLE
cant compile with mingw

### ISSUE THREAD

**Issue by p1plp1** [freeserf/freeserf#506]
error in game.cc, mingw doesnt supports thread lib same way as M$ visual C11 and above, so i added:
#ifndef __MINGW32__
#include <thread>
#else
//todo solve threads
#endif

....
#ifndef __MINGW32__
  Log::Verbose["game"] << "thread #" << std::this_thread::get_id() << " is locking mutex for Game::update_flags";
  mutex.lock();
  Log::Verbose["game"] << "thread #" << std::this_thread::get_id() << " has locked mutex for Game::update_flags";  
  #else
  //todo: add mingw threading support
  #endif	  
  
  etc.
  
  ill add code for mingw compiler, maybe only mutex locking+ unlocking replacement.

**Comment by p1plp1** [comment]
hmm threading solved using lib SDL2, following fixes are required:
freeserf-master\buildgw\src\CMakeFiles\profiler.dir\linklibs.rsp 
add  -lSDL2 switch at end for correct linking,

then edit game.cc following WAY, include section:
#ifndef __MINGW32__
#include <thread>
//namespace std_boost = std;
#else
//fix for mingw
#include <SDL2/SDL.h>
#include <SDL2/SDL_thread.h>
#include <SDL2/SDL_mutex.h>
#endif
....
....
void
Game::update_flags() {

  #ifndef __MINGW32__
  Log::Verbose["game"] << "thread #" << std::this_thread::get_id() << " is locking mutex for Game::update_flags";
  mutex.lock();
  Log::Verbose["game"] << "thread #" << std::this_thread::get_id() << " has locked mutex for Game::update_flags";  
  #else	  
  //mingw threading support  
  SDL_mutex* mut=SDL_CreateMutex();
  SDL_LockMutex(mut);  
  #endif
  ...
  ...
  #ifndef __MINGW32__
  Log::Verbose["game"] << "thread #" << std::this_thread::get_id() << " is unlocking mutex for Game::update_flags";
  mutex.unlock();
  #else
  //mingw threading support  
  SDL_UnlockMutex(mut);  
  SDL_DestroyMutex(mut);  
  #endif
}

**Comment by wdigger** [comment]
Not applicable to this repository.
