### ISSUE TITLE
DOS music doesn't work in linux?

### ISSUE THREAD

**Issue by tlongstretch** [freeserf/freeserf#508]
I thought this was a bug in my fork but when I compiled FreeSerf latest version I see same issue.  None of the music plays if DOS assets used, but Amiga works fine.   I can confirm sdl2mixer is loaded

I remember it working in Windows, I wonder if it is something about my particular linux env.  Does linux DOS music work for anybody else?

I am trying to find old or precompiled FreeSerf linux binaries to see if any version works.  I switched to Amiga so long ago I can't remember if DOS music has  ever worked for me on linux

**Comment by wdigger** [comment]
We have too much linuxes in fact ;)
What distribution you tried on?
What MIDI lib is sdl2_mixer builded in?

**Comment by tlongstretch** [comment]
Nice to see you are still around :)

I am using Centos7u6, gcc7.3.1, sdl2_mixer is built in and Amiga music and all other DOS+Amiga sounds work correctly.  The game runs fine, music simply does not play.  My system uses pulseaudio. 

FreeSerf: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.32

# console output with added debugging:
Info: [audio:SDL_mixer] Playing MIDI track: 0
Warning: [audio.cc] inside play_track, failed to create sound or midi track! track_id 0, source_type 1
Info: [audio:SDL_mixer] Playing MIDI track: 1
Warning: [audio.cc] inside play_track, failed to create sound or midi track! track_id 1, source_type 1
Info: [audio:SDL_mixer] Playing MIDI track: 2
Warning: [audio.cc] inside play_track, failed to create sound or midi track! track_id 2, source_type 1
Info: [audio:SDL_mixer] Playing MIDI track: 3
Error: [data] Could not extract XMI clip: #3
Warning: [audio.cc] inside play_track, failed to create sound or midi track! track_id 3, source_type 1
Info: [audio:SDL_mixer] Playing MIDI track: 4
Warning: [audio.cc] inside play_track, failed to create sound or midi track! track_id 4, source_type 1

create_track(track_id) results in nullptr if I add above check to Audio::Player::play_track function

I'm not sure if the XMI clip is error is relevant.

**Comment by tlongstretch** [comment]
[pid 28691] prctl(PR_SET_NAME, "SDLHotplugALSA\0n") = 0
[pid 28691] open("/etc/alsa/conf.d/50-pulseaudio.conf", O_RDONLY) = 9
[pid 28691] read(9, "# Add a specific named PulseAudi"..., 4096) = 242
[pid 28691] open("/etc/alsa/conf.d/99-pulseaudio-default.conf", O_RDONLY) = 9
[pid 28691] read(9, "# Default to PulseAudio\n\npcm.!de"..., 4096) = 201
[pid 28673] open("/usr/lib64/alsa-lib/libasound_module_pcm_pulse.so", O_RDONLY|O_CLOEXEC) = 9
[pid 28673] open("/root/.pulse/client.conf", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 28673] open("/root/.config/pulse/client.conf", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 28673] open("/etc/pulse/client.conf", O_RDONLY|O_CLOEXEC) = 13
[pid 28673] read(13, "# This file is part of PulseAudi"..., 4096) = 1201
[pid 28673] openat(AT_FDCWD, "/etc/pulse/client.conf.d", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 28673] writev(13, [{"\20\0\5\0\f\0\0\0PULSE_SERVER", 20}], 1) = 20
[pid 28673] writev(13, [{"\20\0\5\0\n\0\0\0PULSE_SINK\0\0", 20}], 1) = 20
[pid 28673] writev(13, [{"\20\0\5\0\f\0\0\0PULSE_SOURCE", 20}], 1) = 20
[pid 28673] writev(13, [{"\20\0\5\0\f\0\0\0PULSE_COOKIE", 20}], 1) = 20
[pid 28673] memfd_create("pulseaudio", MFD_ALLOW_SEALING) = 13
[pid 28673] access("/root/.pulse", F_OK <unfinished ...>
[pid 28673] mkdir("/root/.config/pulse", 0700 <unfinished ...>
[pid 28673] open("/root/.config/pulse", O_RDONLY|O_NOCTTY|O_NOFOLLOW|O_CLOEXEC) = 14
[pid 28673] readlink("/root/.config/pulse/e46638be85584c81af5fa24f91f9de1c-runtime", "/tmp/pulse-PQIFpJ7FtJ1Z", 99) = 23
[pid 28673] lstat("/tmp/pulse-PQIFpJ7FtJ1Z", {st_mode=S_IFDIR|0700, st_size=6, ...}) = 0
[pid 28673] lstat("/root/.config/pulse", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
[pid 28673] lstat("/root/.config/pulse/e46638be85584c81af5fa24f91f9de1c-runtime", {st_mode=S_IFLNK|0777, st_size=23, ...}) = 0
[pid 28673] readlink("/root/.config/pulse/e46638be85584c81af5fa24f91f9de1c-runtime", "/tmp/pulse-PQIFpJ7FtJ1Z", 4095) = 23
[pid 28673] lstat("/tmp/pulse-PQIFpJ7FtJ1Z", {st_mode=S_IFDIR|0700, st_size=6, ...}) = 0
[pid 28673] connect(14, {sa_family=AF_LOCAL, sun_path="/tmp/pulse-PQIFpJ7FtJ1Z/native"}, 110) = -1 ENOENT (No such file or directory)
[pid 28673] connect(14, {sa_family=AF_LOCAL, sun_path="/var/run/pulse/native"}, 110) = -1 ENOENT (No such file or directory)
[pid 28673] write(2, "ALSA lib pulse.c:243:(pulse_conn"..., 37ALSA lib pulse.c:243:(pulse_connect) ) = 37
[pid 28673] write(2, "PulseAudio: Unable to connect: C"..., 50PulseAudio: Unable to connect: Connection refused
[pid 28673] write(2, "ExceptionSDLmixer", 17ExceptionSDLmixer) = 17
[pid 28673] write(2, "[audio:SDL_mixer] Could not open"..., 100[audio:SDL_mixer] Could not open audio device (ALSA: Couldn't open audio device: Connection refused)) = 100

**Comment by tlongstretch** [comment]
I am thinking my pulseaudio works properly and this is some data load issue?

inside create_track, music ends up being a nullptr here:

```
  SDL_RWops *rw = SDL_RWFromMem(midi->get_data(),
                                static_cast<int>(midi->get_size()));
  Mix_Music *music = Mix_LoadMUS_RW(rw, 0);
  if (music == nullptr) {
    Log::Error["audio-sdlmixer.cc"] << "inside AudioSDL::PlayerMIDI::create_track, music is nullptr!";
    return nullptr;
  }
```

**Comment by tlongstretch** [comment]
FIXED!  the answer for me is to install 'timidity' package, I used yum install timidty

I'll make a note of this in the souce code for my fork.  If you have time, it may be worth testing for nullptr when loading music and printing SDL_GetError if nullptr found, and mentioning timidity package.
