### ISSUE TITLE
Missing button to link nearby road with flag

### ISSUE THREAD

**Issue by zdechlak** [freeserf/freeserf#68]
![connection](https://f.cloud.github.com/assets/2237225/560402/0c8c9dfc-c474-11e2-9398-cde64a97c447.png)

**Comment by wdigger** [comment]
If this graphics element is present in DOS resources, it's not too hard for realization.

**Comment by wdigger** [comment]
Dos game resources has this icon, but dos game (and freeserf) have no such use case. In dos game we have no dead ends, road it's always flag to flag path.
